## 03 ``numpy.array`` 基础

In [14]:
import numpy

In [15]:
numpy.__version__

'1.16.2'

In [16]:
import numpy as np

In [17]:
np.__version__

'1.16.2'

### Python List的特点

In [18]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
L[5]

5

In [20]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [21]:
L[5] = "Machine Learning"
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

Python的List不要求存储同样的类型，带来效率问题。

In [22]:
import array
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[5]

5

In [24]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [13]:
arr[5] = "Machine Learning"

TypeError: an integer is required (got type str)

In [25]:
arr[5] = 5.0

TypeError: integer argument expected, got float

``array``的缺点是没有将数据当做向量或者矩阵，不支持基本运算。

### ``numpy.array``

In [26]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [28]:
nparr[5] = "Machine Learning"

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [29]:
nparr.dtype

dtype('int32')

In [30]:
nparr[5] = 5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
nparr.dtype

dtype('int32')

In [32]:
nparr[5] = 3.14
nparr

array([0, 1, 2, 3, 4, 3, 6, 7, 8, 9])

In [34]:
nparr2 = np.array([1, 2, 3.0])
nparr2.dtype

dtype('float64')

In [35]:
nparr2

array([1., 2., 3.])