## 04 创建 ``numpy.array``

In [1]:
import numpy as np

### ``numpy.array``

In [2]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 其他创建 ``numpy.array`` 的方法

#### ``zeros``

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### ones

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### full

In [9]:
np.full((3, 5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [10]:
np.full(fill_value=666, shape=(3, 5))

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

#### arange

In [11]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [12]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
[i for i in range(0, 1, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [14]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [15]:
[i for i in range(0, 10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### linspace 前闭后闭 最后的参数为截取多少个间距相等的数

In [30]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [31]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [32]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### random

##### randint

In [33]:
np.random.randint(0, 10)    # [0, 10)之间的随机数

6

In [34]:
np.random.randint(0, 10, 10)

array([2, 1, 0, 1, 4, 0, 4, 1, 1, 6])

In [35]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
np.random.randint(0, 10, size=10)

array([3, 4, 6, 4, 2, 8, 7, 0, 5, 8])

In [37]:
np.random.randint(0, 10, size=(3,5))

array([[3, 9, 9, 7, 0],
       [6, 4, 4, 0, 4],
       [2, 5, 8, 8, 4]])

In [38]:
np.random.randint(10, size=(3,5))

array([[0, 2, 9, 0, 9],
       [7, 0, 6, 2, 2],
       [4, 9, 4, 8, 4]])

##### seed

In [39]:
np.random.seed(666)

In [40]:
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [42]:
np.random.seed(666) #确定种子，每次的随机值都是一致的
np.random.randint(0, 10, size=(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

##### random

In [47]:
np.random.random(10)

array([0.66673747, 0.87287954, 0.52109719, 0.75020425, 0.32940234,
       0.29130197, 0.00103619, 0.6361797 , 0.97933558, 0.91236279])

In [48]:
np.random.random((3,5))

array([[0.39925165, 0.40322917, 0.33454934, 0.72306649, 0.96832961],
       [0.86766484, 0.79123524, 0.44446092, 0.95619151, 0.73353358],
       [0.71210247, 0.2427146 , 0.57043673, 0.57773404, 0.89274848]])

##### normal 从正态分布（高斯分布）中抽取随机样本

In [59]:
np.random.normal()

-0.16045654604799553

In [60]:
np.random.normal(10, 100)

10.592352841953147

In [64]:
np.random.normal(0, 1, (3, 5))

array([[-0.65179635, -0.47064834,  1.09057819,  1.2267939 ,  0.25893563],
       [-1.44545669, -0.26378654,  1.71971234,  0.4855902 ,  0.52281208],
       [ 1.51131644, -0.82449495,  0.09383679,  1.75190746, -1.21352598]])

`np.random.<TAB>` 查看random中的更多方法

In [40]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap